[[headers]]
  for = '/*' # all files
  [headers.values]
    Cache-Control = 'public, max-age=3600'
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; img-src data: https:; frame-src https:; object-src 'none';"
    Permissions-Policy = ''
    Referrer-Policy = 'strict-origin-when-cross-origin'
    Strict-Transport-Security = 'max-age=31536000; preload; includeSubDomains'
    X-Content-Type-Options = 'nosniff'
    X-Xss-Protection = '1; mode=block'

# Set hashed assets to be immutable
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Other asset caching
[[headers]]
  for = "*.woff2" # fonts
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
[[headers]]
  for = "/meta/*" # meta files
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
